Improve setup generator

diff --git a/libexec/reno-generate b/libexec/reno-generate
--- a/libexec/reno-generate
+++ b/libexec/reno-generate
@@ -71,28 +71,50 @@ generate_setup() {
   generate "$INFILL_DIR/setup.sh" "$(cat <<DATA
 #!/usr/bin/env bash
 
-RENO_REPO="$reno_repo"
-INSTALLER="$installer"
-INFILL_REPO="$infill_repo"
-INFILL_ARCHIVE="$infill_archive"
+set -eu
 
+INSTALL_DIR="\$HOME/.reno"
+AUTO_INSTALL=
+AUTO_YES=
+
+# install via git
+REPOSITORY="$reno_repo"
+INFILL_REPOSITORY="$infill_repo"
+
+# install from archive
+INSTALLER="$installer"
+INFILL_ARCHIVE="$infill_archive"
+INFILL_ARCHIVE_FORMAT="auto"
 DATA
 cat <<'DATA'
-RENO_DIR="$HOME/.reno"
-INFILL_DIR="$HOME/.infill"
+
+export RENO_YES=${AUTO_YES:-}
 
 if type git > /dev/null 2>&1; then
-  if [[ -e $RENO_DIR ]]; then
+  if [[ -e $INSTALL_DIR || -L $INSTALL_DIR ]]; then
     echo "Found reno directory. skipping reno installation."
   else
-    git clone $RENO_REPO $RENO_DIR
-    $RENO_DIR/install.sh
+    git clone "$REPOSITORY" "$INSTALL_DIR"
+    "$INSTALL_DIR/install.sh"
   fi
-  $RENO_DIR/bin/reno init $INFILL_REPO
+
+  if [[ $INFILL_REPOSITORY && $INFILL_REPOSITORY != "YOUR-INFILL-REPOSITORY" ]]; then
+    "$INSTALL_DIR/bin/reno" init "$INFILL_REPOSITORY"
+  fi
 else
-  echo -n "Git not found. Do you want to import from an archive? [y/N] "
-  read input
+  if [[ ! $INSTALLER ]]; then
+    echo "Git not found."
+    exit 1
+  fi
+
+  if [[ $AUTO_YES ]]; then
+    echo "Git not found. Import from archive."
+  else
+    echo -n "Git not found. Do you want to import from an archive? [y/N] "
+    read input
+  fi
   [[ $input = "y" || $input = "Y" ]] || exit 1
+
   if type curl > /dev/null 2>&1; then
     bash -c "$(curl -L $INSTALLER)"
   elif type wget > /dev/null 2>&1; then
@@ -101,7 +123,14 @@ else
     echo "Not found git, wget, curl. Aborting"
     exit 1
   fi
-  $RENO_DIR/bin/reno init $INFILL_ARCHIVE --type archive
+
+  if [[ $INFILL_ARCHIVE && $INFILL_ARCHIVE != "YOUR-INFILL-ARCHIVE" ]]; then
+    "$INSTALL_DIR/bin/reno" init "$INFILL_ARCHIVE" --type archive --format "$INFILL_ARCHIVE_FORMAT"
+  fi
+fi
+
+if [[ $AUTO_INSTALL ]]; then
+  "$INSTALL_DIR/bin/reno" install
 fi
 DATA
   )"
